version: "3"

services:
  nginx:
    image: nginx:latest
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - tomcat
    restart: always

  tomcat:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=abhiram*68*
      - MYSQL_DATABASE=servlet_application
    volumes:
      - ./myapp:/usr/local/tomcat/webapps/myapp
      # - ./index.html:/usr/local/tomcat/webapps/ROOT/index.htm
    ports:
      - "8180:8180"
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=abhiram*68*
      - MYSQL_DATABASE=servlet_application
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
