apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat
  labels:
    app: tomcat
spec:
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
        - name: tomcat
          image: $APP_IMAGE
          ports:
            - containerPort: 8085
          env:
            - name: DB_HOST
              value: "servlet_application"
            - name: DB_PORT
              value: $DB_PORT
            - name: DB_NAME
              value: $DB_NAME
            - name: DB_USER
              value: $DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-password
                  key: password
